[build]
  publish = "public"
  functions = "netlify-functions"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, X-Device-Fingerprint, X-Session-Key, X-Timestamp, X-Signature"
    Access-Control-Allow-Methods = "POST, GET, OPTIONS"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 