[build]
  functions = "netlify-functions"
  publish = "public"

[functions]
  directory = "netlify-functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, X-Device-Fingerprint, X-Session-Key, X-Timestamp, X-Signature"
    Access-Control-Allow-Methods = "POST, GET, OPTIONS" 